# Generated by Django 5.1.3 on 2024-12-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_administrator_middle_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingcriterion',
            name='criteria_type',
            field=models.CharField(choices=[('WW', 'Written Works'), ('PT', 'Performance Tasks'), ('QE', 'Quarterly Exam')], max_length=2, unique=True),
        ),
    ]
